version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: pos_koperasi_db
    restart: always
    environment:
      POSTGRES_DB: pos_koperasi
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
